include ../../build/arch.make
include flags.make

SRCS =

CXX_SRCS = main.cpp
CXX_SRCS += AList1.cpp
CXX_SRCS += AListIterator1.cpp
CXX_SRCS += HttpdRequest1.cpp
CXX_SRCS += String1.cpp
CXX_SRCS += DynObject1.cpp
CXX_SRCS += JsonFlattener1.cpp

CPPFLAGS += -I../../src/toolbox/include

NAME = toolbox_utest
BUILD_TYPE = exe

include ../../build/makefile.gen

