
default: all

all:
	cd calloc1 && make all
	cd malloc1 && make all
	cd realloc1 && make all
	cd realloc2_null && make all
	cd new1_nothrow && make all
	cd new2_throw && make all


run:
	cd calloc1 && make run
	cd malloc1 && make run
	cd realloc1 && make run
	cd realloc2_null && make run
	cd new1_nothrow && make run
	cd new2_throw && make run

clean:
	cd calloc1 && make cleanall
	cd malloc1 && make cleanall
	cd realloc1 && make cleanall
	cd realloc2_null && make cleanall
	cd new1_nothrow && make cleanall
	cd new2_throw && make cleanall

